### ISSUE TITLE
 Pickling of "tango._tango.DeviceAttribute" instances is not enabled

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#447]
Hi,

After longer run of  some taurus application I get the following error:

    jkotan@haso228k:~/p65gui/my$ ./P65guiControl.py --taurus-log-level==debug
    MainThread     INFO     2017-04-07 16:58:55,809 TaurusRootLogger: Using "PyQt4" for Qt
    MainThread     INFO     2017-04-07 16:58:56,077 TaurusApplication: Logs will be saved in /home/jkotan/tmp/P65guiControl.py/P65guiControl.py.log
    MainThread     INFO     2017-04-07 16:58:56,078 TaurusGui: Resetting unresponsive socket with key "__socket_jkotan-P65guiControl.py__"
    MainThread     INFO     2017-04-07 16:58:56,078 TaurusGui: Registering as single instance with key "__socket_jkotan-P65guiControl.py__"
    MainThread     WARNING  2017-04-07 16:58:56,079 TaurusGui: Cannot import taurus.qt.qtgui.console. The Console Panel will not be available
    MainThread     INFO     2017-04-07 16:58:56,081 TaurusGui: MainWindow settings restored
    MainThread     INFO     2017-04-07 16:58:56,082 TaurusApplication: Logs will be saved in /home/jkotan/tmp/P65 Beamline Control HB/P65 Beamline Control HB.log
    MainThread     INFO     2017-04-07 16:58:56,082 TaurusGui: Registering as single instance with key "__socket_jkotan-P65 Beamline Control HB__"
    MainThread     INFO     2017-04-07 16:58:56,083 TaurusGui: Panel with name "Manual" already exists. Reusing.
    push_event generated the following python exception:
    MainThread     ERROR    2017-04-07 16:58:58,146 LogExceptHook: Unhandled exception:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py", line 473, in push_event
    listeners=listeners)
    File "/usr/lib/python2.7/dist-packages/taurus/core/taurusmodel.py", line 258, in fireEvent
    l(self, event_type, event_value)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py", line 70, in recordDataReceived
    res = BaseDoor.recordDataReceived(self, s, t, v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 614, in recordDataReceived
    return self._processRecordData(v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 626, in _processRecordData
    data = codec.decode(data)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 800, in decode
    data = codec.decode(data, *args, **kwargs)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 226, in decode
    return format, bz2.decompress(data[1])
    IOError: invalid data stream
    Fri Apr  7 16:59:37 2017: Tango::ZmqEventConsumer::push_heartbeat_event() timeout on channel monitor of tango://haso228k.desy.de:10000/dserver/macroserver/haso228k
    Fri Apr  7 16:59:38 2017: Tango::ZmqEventConsumer::push_heartbeat_event() timeout on channel monitor of tango://haso228k.desy.de:10000/dserver/macroserver/haso228k
    Dummy-1        INFO     2017-04-07 16:59:38,429 haso228k:10000.p09/door/haso228k.01.Debug: Activating polling. Reason: API_EventTimeout
    Dummy-1        INFO     2017-04-07 16:59:38,432 haso228k:10000.p09/door/haso228k.01.Error: Activating polling. Reason: API_EventTimeout
    Dummy-1        INFO     2017-04-07 16:59:38,434 haso228k:10000.p09/door/haso228k.01.Info: Activating polling. Reason: API_EventTimeout
    Dummy-1        INFO     2017-04-07 16:59:38,436 haso228k:10000.p09/door/haso228k.01.Input: Activating polling. Reason: API_EventTimeout
    Dummy-1        INFO     2017-04-07 16:59:38,438 haso228k:10000.p09/door/haso228k.01.Output: Activating polling. Reason: API_EventTimeout
    Dummy-1        INFO     2017-04-07 16:59:38,441 haso228k:10000.p09/door/haso228k.01.RecordData: Activating polling. Reason: API_EventTimeout
    push_event generated the following python exception:
    Dummy-1        ERROR    2017-04-07 16:59:39,449 LogExceptHook: Unhandled exception:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py", line 473, in push_event
    listeners=listeners)
    File "/usr/lib/python2.7/dist-packages/taurus/core/taurusmodel.py", line 258, in fireEvent
    l(self, event_type, event_value)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py", line 70, in recordDataReceived
    res = BaseDoor.recordDataReceived(self, s, t, v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 614, in recordDataReceived
    return self._processRecordData(v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 626, in _processRecordData
    data = codec.decode(data)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 800, in decode
    data = codec.decode(data, *args, **kwargs)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 226, in decode
    return format, bz2.decompress(data[1])
    IOError: invalid data stream
    Segmentation fault

then in spock

    jkotan@haso228k:~/p65gui/my$ spock
    MainThread     INFO     2017-04-07 17:01:43,852 TaurusRootLogger: Using "PyQt4" for Qt
    Spock 2.2.4.4 -- An interactive laboratory application.

    help      -> Spock's help system.
    object?   -> Details about 'object'. ?object also works, ?? prints more.

    IPython profile: spockdoor

    Connected to p09/door/haso228k.01
    push_event generated the following python exception:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py", line 473, in push_event
    listeners=listeners)
    File "/usr/lib/python2.7/dist-packages/taurus/core/taurusmodel.py", line 258, in fireEvent
    l(self, event_type, event_value)
    File "/usr/lib/python2.7/dist-packages/sardana/spock/spockms.py", line 515, in recordDataReceived
    res = SpockBaseDoor.recordDataReceived(self, s, t, v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py", line 70, in recordDataReceived
    res = BaseDoor.recordDataReceived(self, s, t, v)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 614, in recordDataReceived
    return self._processRecordData(v)
    File "/usr/lib/python2.7/dist-packages/sardana/spock/spockms.py", line 496, in _processRecordData
    return BaseDoor._processRecordData(self, data)
    File "/usr/lib/python2.7/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 626, in _processRecordData
    data = codec.decode(data)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 800, in decode
    data = codec.decode(data, *args, **kwargs)
    File "/usr/lib/python2.7/dist-packages/taurus/core/util/codecs.py", line 226, in decode
    return format, bz2.decompress(data[1])
    IOError: invalid data stream

    If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org

    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.

    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

    p09/door/haso228k.01 [2]: %config Application.verbose_crash=True
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
    ERROR: Pickling of "tango._tango.DeviceAttribute" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)

Does sardana/taurus try to make pickle from DeviceAttribute?

To get the sardana working back I had to restart it. 

I run sardana 2.2.4 without SEP6 and with Tango 9.

Bests,
Jan

**Comment by cpascual** [comment]
Hi, the mention to the pickling got me confused... AFAIK, a DeviceAttribute cannot be pickled, by design...
Looking at the python traces, the problem seems to appear during a bz2 decoding triggered by an event received by the BaseDoor.

I seems that the value received in such event contains something that cannot be encoded/decoded.

@jkotan would you be able to show us a way to reproduce the problem within the [taurus-test docker](https://hub.docker.com/r/cpascual/taurus-test/) ?

If not, I am afraid you may need to debug it yourself :(

**Comment by jkotan** [comment]
I'll do my best but this error appears on my computer not so often so for me it is hard to reproduce it.

**Comment by jkotan** [comment]
Hi,

It looks like from time to time my RecordData attribute of my door get `value` equal to  array of zerors. i.e.

('bz2_pickle',  '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 ... \x00\x00\x00\x00\x00\x00\x00\x00')

in that case when I start taurusgui macrogui with set MacroServer and Door in XML config file I get
the above mentioned error (IOError: invalid data stream).

Bests,
Jan

**Comment by reszelaz** [comment]
@jkotan it will help to know which was the last macro run on the Door and if it finished correctly i.e. no user stop/abort, exception, etc. Could you provide this info, please?

**Comment by jkotan** [comment]
Hi Zibi,

For my test I use only `ascan` macro from macro executor gui. It is quite random (normally I do not get any error). But if I get the error the `RecordData` event in push_event of `taurus/core/tango/tangoattribute.py` is ('bz2_pickle', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 ... \x00\x00\x00\x00\x00\x00\x00\x00')
while printout in read_RecordData of sardana/tango/macroserver/Door.py gives me none-zero data.
From time to time I can see also zero data of RecordData in jive. 
Currently for test I use pytango 9.2.0 (standard for stretch). I will try to reproduce it with 9.2.2

Bests,
Jan

**Comment by jkotan** [comment]
Hi, 
i've just noticed that sardana does not work with PyTango 9.2.2 because it looks like 9.2.2 is not backward compatible with 9.2.0, i.e. in 9.2.2 
    
    from PyTango import seqStr_2_obj

does not work anymore and I get 

    jkotan@stretch-jk:~$ Pool stretch-jk
    Traceback (most recent call last):
      File "/home/jkotan/testsar/bin/Pool", line 11, in <module>
	load_entry_point('sardana==2.2.5a0', 'console_scripts', 'Pool')()
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/pool/__init__.py", line 107, in main
	run(start_time=datetime.datetime.now())
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/pool/__init__.py", line 100, in main_pool
	name=SERVER_NAME)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/core/util.py", line 1045, in run
	prepare_func(tango_util)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/pool/__init__.py", line 66, in prepare_pool
	from .Controller import ControllerClass, Controller
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/pool/Controller.py", line 49, in <module>
	from PoolDevice import PoolDevice, PoolDeviceClass
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5a0-py2.7.egg/sardana/tango/pool/PoolDevice.py", line 37, in <module>
	from PyTango import Util, DevVoid, DevLong64, DevBoolean, DevString, \
    ImportError: cannot import name seqStr_2_obj
    terminate called after throwing an instance of 'omni_thread_fatal'

https://github.com/tango-controls/pytango/issues/144


Best reagrds,
Jan

**Comment by reszelaz** [comment]
The `RecordData` attribute usually don’t send events encoded with `bz2_pickle`. The usual events are encoded with `json` - these are the ones coming from the `JsonRecorder`. The `bz2_pickle` encoding takes place when the attribute is read. So if the client fails in the `push_event`, it must be the first event that corresponds to the event subscription moment and the forced attribute readout.

If this error appears after a long application’s up time, I suspect that something makes the `RecordData` event subscription. From the initial logs we can observe a chain of `API_EventTimeout` errors:

```
Dummy-1        INFO     2017-04-07 16:59:38,429 haso228k:10000.p09/door/haso228k.01.Debug: Activating polling. Reason: API_EventTimeout
```

These may occur if the MacroServer gets crashed or there is a problem with delivering the Tango heartbeat event. Do you think that there could be some problems with the events or maybe the server crash?

**Comment by jkotan** [comment]
This error appears during starting `taurusgui macrogui` which is set from an xml file (GUI window is not yet displayed).  I've not noticed  crash/errors of MacroServer /Pool servers. I use pure ZMQ events (without notifyd). So it looks like something with events.

**Comment by jkotan** [comment]
But I've noticed that in jive when I want to read `RecordData` attribute from time to time it takes longer.

**Comment by reszelaz** [comment]
> This error appears during starting taurusgui macrogui

Is it reproducible? I mean if you try to start the application again and again the error is the same?

**Comment by jkotan** [comment]
It quite randomly reproducible, i.e. usually it does not appear but let say after 50th of the start it appears (this 50 is only example). But the error is always the same.

**Comment by reszelaz** [comment]
To stress test it you could try something like this:

```
import PyTango
from taurus.core.util.codecs import CodecFactory

def cb(event_data):
    if event_data.err:
        print "event error"
        return
    print CodecFactory().decode(event_data.attr_value.value)

door = PyTango.DeviceProxy("door/zreszela/1")

while True:
    id_ = door.subscribe_event("RecordData", PyTango.EventType.CHANGE_EVENT, cb, stateless=True)
    door.unsubscribe_event(_id)
```

**Comment by jkotan** [comment]
Yes, I can reproduce the error. Of course before I have to run ascan macro. Sometime it does not happen for longer time (or at all),  but some time one after the other  (it  has to be an inteference with something else).

    import PyTango
    from taurus.core.util.codecs import CodecFactory

    def cb(event_data):
        if event_data.err:
            print "event error"
            return
        w = CodecFactory().decode(event_data.attr_value.value)

    door = PyTango.DeviceProxy("door/stretch-jk/1")

    while True:
        id_ = door.subscribe_event("RecordData", PyTango.EventType.CHANGE_EVENT, cb, stateless=True)
        door.unsubscribe_event(id_)

I removed print-out to see the error message and made fix for `id_` and `_id`.

**Comment by jkotan** [comment]
By I get almost very fast this error when I run two such scripts simultaneously. They interfare each other.

**Comment by reszelaz** [comment]
How many points had your `ascan`? I can not reproduce it with a scan of just 2 points. I had tried with two scripts running in parallel and nothing happens.

**Comment by jkotan** [comment]
I execute

    ascan mot03 0.0 10.0 10 0.01

on my stretch VM. Motor is created by `sar_demo`. On this VM I run also jive, firefox which may slow down it.

**Comment by jkotan** [comment]
*        mntgrp01    ct01 ct01, ct02, ct03, oned01, zerod01, ct05

**Comment by jkotan** [comment]
I could reproduce the error on other stretch computer using develop branches of taurus/sardana and python-pytango (9.2.0-2) by:

    # first terminal
    Pool stretch

    # second terminal
    MacroServer stretch

    # third terminal
    spock
    # sar_demo
    # expconf
    ## create mg01
    ##  +  mg01    ct01 ct01, ct02, ct03, ct04, oned01, zerod01
    ## ScanDir = /tmp/  ScanFile = myw.spec // important
    #
    # ascan mot03 0 10 10 0.1
    #
    python ./test.py (the above test)

    # fourth terminal
    python ./test.py (the above test)

and I get after some time

     push_event generated the following python exception:
    Traceback (most recent call last):
      File "./test.py", line 8, in cb
	w = CodecFactory().decode(event_data.attr_value.value)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.0.4a0-py2.7.egg/taurus/core/util/codecs.py", line 925, in decode
	data = self.getCodec(data[0]).decode(data, *args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.0.4a0-py2.7.egg/taurus/core/util/codecs.py", line 798, in decode
	data = codec.decode(data, *args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.0.4a0-py2.7.egg/taurus/core/util/codecs.py", line 228, in decode
	return format, bz2.decompress(data[1])
    IOError: invalid data stream

**Comment by jkotan** [comment]
During the tests I had one case where instead of the standard error MacroServer crashed with SEG FAULT.

**Comment by reszelaz** [comment]
I was running two scripts in parallel the whole morning and in my case, they did not crash. I use the same software versions as you.

Now I realized your comment "important" next to the ScanDir and ScanFile - I was running the test without it. Now I have re-launch the tests after a previous execution of the ascan storing the data into a file. Why do you think that the file is important in order to reproduce it? The RecordData attribute is unrelated to the file.

**Comment by jkotan** [comment]
Sorry, // important  is not related.  I can reproduce it  without setting ScanDir/ScanFile. And also on jessie (wit pytango 9.2 also with old taurus(3.7) and sardana (before mg changes) ) and in stretch with pytango 9.2.1.
But sometimes it really hard to get it, e.g. with 9.2.1 I run a few  test scripts simultaneously with  ascan command in spock.
I will try to add some printouts into pytango. I don't see any reason of this problem in sardana/taurus.

**Comment by reszelaz** [comment]
> But sometimes it really hard to get it, e.g. with 9.2.1 I run a few test scripts simultaneously with ascan command in spock.

Do you run ascan in parallel to the test scripts?

> I will try to add some printouts into pytango. I don't see any reason of this problem in sardana/taurus.

That would be great if you could debug it. I have very limited time in the following 2 weeks. Thanks!

**Comment by jkotan** [comment]
Yes. for 9.2.1 it is much harder to reproduce the bug at it mostly appears when I run ascan in parallel to the test scripts (for 9.2.0 it was much easier).

**Comment by reszelaz** [comment]
Ahh ok. I was running my tests while there was no macro running at that moment. If we run the scan and read the RecordData simultaneously there may be something wrong, but I'm not sure.

Basically, the scan fills a dictionary with new records (in our case multiple scalars and one spectrum per record). At the same time, from another thread, we pickle the same dictionary. I'm not sure if this is safe and I will need to investigate it...

**Comment by jkotan** [comment]
After adding printouts into pytango it looks like the problem comes from (py)tango so I've created a ticket https://github.com/tango-controls/pytango/issues/147

**Comment by reszelaz** [comment]
I still could not check the thread safeness of picking a dict object while it is being modified. I have just found [this *open* answer](https://stackoverflow.com/questions/23754086/mulithreading-environment-and-modules-like-pickle-or-json?answertab=active#tab-top):

> Using pickle and json will work fine in a multi-threaded environment (but probably is not thread-safe so make sure the data you're pickling can't changing at the time, for example by using a lock). The catch is that you will be restricted to the kind of data you can actually save to disk.

If it is not thread safe it could be the origin of the bug that you encountered.

**Comment by jkotan** [comment]
Hi,

for me it looks like the reason of this error is not pythonic behavior of `attr.set_value()` from `pytango` for `DevEncoded` (or in other words wrong usage of pytango API by sardana), i.e.

looking at `pytango/cppTango/omniorb` I can only see that  `encoded_format` of `DevEncoded`  is copied while for  `encoded_data` of  `DevEncoded` only its pointer is copied (to avoid coping of data).

Therefore, when `data` in  `read_RecordData` is release by `gc` it can be overwrite by something else and tango will send an event with wrong data. 

The simplest workaround would be

    diff --git a/src/sardana/tango/macroserver/Door.py b/src/sardana/tango/macroserver/Door.py
    index c411a18..8582760 100644
    --- a/src/sardana/tango/macroserver/Door.py
    +++ b/src/sardana/tango/macroserver/Door.py
    @@ -349,6 +349,7 @@ class Door(SardanaDevice):
                 throw_sardana_exception(mse)
     
             attr.set_value(*data)
    +        self.__buf_data = data
     
         def read_MacroStatus(self, attr):
             attr.set_value('', '')
    
but of course it would be better to fix it in `pytango` (make it more pythonic).

**Comment by reszelaz** [comment]
Sorry for replying so late but after the holidays I had quite a few urgent issues to attend.

I saw in the PyTango issue that this was confirmed as a bug in PyTango. So at some point, we could expect to have it fixed there. Meanwhile, your workaround looks reasonable. Could you propose a PR, I will then merge it immediately.
