### PR TITLE
Add protection on parameter info reading

### LINKED ISSUE #941: macroexecutor yellow line reports errors
If you try to write a macro using the yellow line of the macroexcutor it reports theses errors
```
Traceback (most recent call last):
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 382, in textChanged
    self.validateAllExpresion()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 284, in validateAllExpresion
    param_info = macro_params_info[counter-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 382, in textChanged
    self.validateAllExpresion()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 269, in validateAllExpresion
    macro_params_info = macro_obj.getElementInfo(mlist[0]).parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
```

The bug seems to be introduced in the PR #876

### PR DESCRIPTION
**Pull request by rhomspuron**
Avoid exception raising during the macro typing on the macroexecutor widget. It resolves #941

### CODE REVIEW

**Comment by reszelaz** [comment]
Great, now it works without problems! Thanks! Merging..
