### ISSUE TITLE
AttributeError  in senv

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#434]
Hi,

in sardana 2.2.4 when we want to set a environment variable with its value containing '.' we get the following error:

    p09/door/haso228k.01 [1]: senv ScanFile water.nxs
    AttributeError: 'str' object has no attribute 'nxs'
    (For more detailed information type: python_error)

    p09/door/haso228k.01 [2]: python_error
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-f499fc45b872> in <module>()
    ----> 1 get_ipython().magic(u'senv ScanFile water.nxs')

    /usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
       2203         magic_name, _, magic_arg_s = arg_s.partition(' ')
       2204         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
    -> 2205         return self.run_line_magic(magic_name, magic_arg_s)
       2206 
       2207     #-------------------------------------------------------------------------
    
    /usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in run_line_magic(self,     magic_name, line)
       2124                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
       2125             with self.builtin_trap:
    -> 2126                 result = fn(*args,**kwargs)
       2127             return result
       2128 

    /usr/lib/python2.7/dist-packages/sardana/spock/spockms.pyc in macro_fn(parameter_s, name)
        583         else:
        584             def macro_fn(parameter_s='', name=macro_name):
    --> 585                 parameters = split_macro_parameters(parameter_s)
        586                 door = genutils.get_door()
        587                 door.runMacro(macro_name, parameters, synch=True)

    /usr/lib/python2.7/dist-packages/sardana/spock/spockms.pyc in split_macro_parameters(parameters_s)
        639         params_str = params_str.replace("[,", "[").replace(",]", "]").replace(
        640             "][", "],[")
    --> 641         macro_params = eval(params_str, globals(), Reflector())
        642         if type(macro_params) == list:
        643             new_params = []
    
    /usr/lib/python2.7/dist-packages/sardana/spock/spockms.pyc in <module>()
    
    AttributeError: 'str' object has no attribute 'nxs'

Without  '.' or with quatas 

    senv ScanFile \"water.nxs\"

it works but it is harder to get a list, i.e.

      senv ScanFile  "[\"water.nxs\",\"water.fio\"]" 

creates a string.

**Comment by jangarrevoet** [comment]
Similar issue when it contains a '/' like when you want to set ScanDir.

**Comment by reszelaz** [comment]
This bug was introduced with #405 . The eval resulted problematic, so I propose to go for a proper parser. I have implemented one [here]("https://github.com/reszelaz/parser/blob/master/src/parser.py"). Now it also covers strings encapsulated in quotes. It could be used instead of the `split_macro_parameters` function.

**Comment by jkotan** [comment]
Hi Zibi,

it looks nice. Does setting of multiple files for ScanFile work as well? How do you do it? Maybe you could add assert statement for this case as well.

Cheers,
Jan

**Comment by jkotan** [comment]
What I meant it looks like only 

    "ScanFile ['file1.nxs' 'file2.fio']"

works OK. But if we going to add a complicated parser why not to support also more pythonic cases like

    "ScanFile ['file1.nxs','file2.fio']"   

or

    "ScanFile ['file1.nxs', 'file2.fio']"   

?

Cheers,
Jan

**Comment by reszelaz** [comment]
Setting of multiple files works as before:

`senv ScanFile "['file.nxs', 'file.dat']"`.

The new parser provides two functionalities. First, it is able to parse parameters as they were passed before introducing the new, complementary syntax. Basically it does the same as ipython's `genutils.arg_split`. Second, it is able to parse repeat parameters grouped by the square brackets. Both the space and the comma were identified as the possible separators of the elements within the square brackets. This topic was under discussion in this [thread](https://sourceforge.net/p/sardana/mailman/message/35559427/) and in #405. Finally the implementation was done with the space.

Regarding the `senv` macro, it is a little bit special. It uses the python `eval` on the server side, which I think is not safe... It has two parameters: the environment variable and the value(s) - repeat parameter (one or more values can be passed to the environment variable). If only one is passed it is directly evaluated. If multiple are passed, they are concatenated to form a string representation of a touple of these values which is later evaluated. We may easily change the macro so it directly pass the list of strings to the environment. This way it would be possible to pass sequences to the environment variables like this:

`senv ScanFile file.nxs file.dat # using the old syntax for repeat parameters`
`senv ScanFile [file.nxs file.dat] # using the new syntax for repeat parameters`

But I think that setting the scan files in a user friendly way could be easily achieved with a new macro called `newfile`. We have already discussed that on the Sardana Workshop in 2015 and the Community was in favor of this. Using this macro to set multiple files would look like:

`newfile file.nxs file.dat`

What do you think about the `newfile` macro? Any volonteer to create a PR? :)

**Comment by reszelaz** [comment]
#436 tries to solve this issue.

**Comment by jkotan** [comment]
Hi Zibi,

It looks like 

    senv ScanFile "[\"file.nxs\", \"file.dat\"]"

does not work anymore so this replace of parser is not backward compatible.

Cheers,
Jan

**Comment by jkotan** [comment]
Hi,

Also 

    senv ScanFile file.nxs file.dat # using the old syntax for repeat parameters
    senv ScanFile [file.nxs file.dat] # using the new syntax for repeat parameters

create `str` instead of `list`. Thus, only

    senv ScanFile "['file.nxs', 'file.dat']"

works correctly.

Bests,
Jan

**Comment by reszelaz** [comment]
I confirm the backwards compatibility problem from your first comment. It will require modifiations in the parser. 

In order to make the examples from your second comment work, we will need to change the `senv` macro. Maybe I was not clear in my [comment](https://github.com/sardana-org/sardana/issues/434#issuecomment-286260481), but that examples are not something what should already work. So I don't see it as a problem of the parser but of the `senv` macro itself. The said change may be a little bit delicate, preciselly from the backwards compatibility point of view. So in order to provide a user friendly way of setting the files, I would go for the `newfile` macro approach.
