### ISSUE TITLE
sardanaeditor error with Sardana 3.0.3, AttributeError: 'SardanaEditor' object has no attribute '_undocked_window'

### ISSUE THREAD

**Issue by TacHuynh** [sardana-org/sardana#1420]
python3 -m sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor lab-01

MainThread     INFO     2020-09-23 05:01:48,151 TaurusRootLogger: Using PyQt5 (v5.9.2 with Qt 5.9.7 and Python 3.8.3)
/home/fbggroup/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor' found in sys.modules after import of package 'sardana.taurus.qt.qtgui.extra_sardana', but prior to execution of 'sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
MainThread     WARNING  2020-09-23 05:01:48,969 TaurusRootLogger: <frozen importlib._bootstrap>:219: DeprecationWarning: taurus.core.util.argparse is deprecated since 4.5.4. Use argparse or (better) click instead

Traceback (most recent call last):
  File "/home/fbggroup/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/fbggroup/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/sardana-3.0.3-py3.8.egg/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 588, in <module>
    main()
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/sardana-3.0.3-py3.8.egg/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 580, in main
    w = demo(args[0])
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/sardana-3.0.3-py3.8.egg/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 550, in demo
    test = SardanaEditor()
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/sardana-3.0.3-py3.8.egg/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 147, in __init__
    self.call__init__wo_kw(TaurusBaseEditor, parent)
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/taurus-4.7.0-py3.8.egg/taurus/core/util/object.py", line 62, in call__init__wo_kw
    klass.__init__(self, *args)
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/taurus-4.7.0-py3.8.egg/taurus/qt/qtgui/editor/tauruseditor.py", line 65, in __init__
    self.editor_splitter = EditorSplitter(self, self, self.menu_actions,
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/editor.py", line 3008, in __init__
    self.editorstack = EditorStack(self, menu_actions)
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/editor.py", line 469, in __init__
    self.__get_split_actions()
  File "/home/fbggroup/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/editor.py", line 1603, in __get_split_actions
    if plugin._undocked_window is not None:
AttributeError: 'SardanaEditor' object has no attribute '_undocked_window'

**Comment by reszelaz** [comment]
Hi @TacHuynh,

First of all many thanks for trying the very recent release.

I think you are hitting problems in the sardanaeditor when running it with the recent spyder versions - https://github.com/sardana-org/sardana/issues/909.

From the notes I see that it should work with spyder 3.1.3 (for example the version which comes with Debian Stretch).
We have never invested time in fixing this and in finishing this witdget in general.

Soon we plan to decide on whether to continue its development or to abandon it. This will depend on the user's feedback from the [sardana-questionnaire](https://sourceforge.net/p/sardana/mailman/message/37111185/).

Cheers!

**Comment by TacHuynh** [comment]
Thanks for your reply.
I am learning the Sardana system to see if it work with my tango test set up, particular the sequencer.
so much to investigate!
Tac.
